### PR TITLE
Changes to make it available to delphi 6

### PR DESCRIPTION
**Pull request by andreluisfc**
Hello there, i've made some changes on the component to make it installable on Delphi 6.
Basically needed to change some types that is available only D7 UP and changed some refs...

All the changes got surrended by the {$IFNDEF DELPHI7_UP} to doesnt affect the original functionality.

Note that i've dont use the FMX version, so only changed VCL version of the code.

Its not the prettier implementation but its working and i'm sending it to you just to you know that its possible and maybe implement it the right way.

Thanks!!

### CODE REVIEW

**Comment by salvadordf** [comment]
Thanks for this pull request!

Please, add your modifications to the latest CEF4Delphi version. 
This PR is based on CEF4Delphi 122.1.10 and the latest is 122.1.13 which adds a few bug fixes.

**Comment by andreluisfc** [comment]
Got it...
Already refreshed my master.

**Comment by salvadordf** [comment]
There are building issues with Lazarus and I also have to replace the PosEx function with a new function in order to avoid copyright problems.

I'll add all your changes manually.

Thank you so much! :D

**Comment by salvadordf** [comment]
I also omitted the modifications to the files in the packages directory. 

Delphi 6 user should install CEF4Delphi using the same instructions as Delphi 7 users, that is, opening CEF4Delphi.dpk, building and installing the package.

Let me know in our forum if I missed something.

**Pull request closed without merging**
